import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import VercelLogo from "../public/vercel.svg";
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>Static pages</h2>
        <div className={styles.block}>
          <Link href={{ pathname: "/static/[page]", query: { page: "SSG" } }}><a>Page SSG</a></Link>
          <Link href={{ pathname: "/static/[page]", query: { page: "ISR" } }}><a>Page ISR</a></Link>
        </div>
        <h2>Dynamic pages</h2>
        <div className={styles.block}>
          <Link href={{ pathname: "/dynamic/[page]", query: { page: "Dynamic" } }}><a>Page Dynamic</a></Link>
        </div>
      </main >

      <footer className={styles.footer}>
        <a
          href="#"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src={VercelLogo} alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div >
  )
}

export default Home